# 太上老君系统 - 最小化部署配置
# 仅包含基础设施服务，用于测试和开发

version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: laojun-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-laojun}
      POSTGRES_USER: ${DB_USER:-laojun}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-laojun123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      # 性能优化
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - laojun-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-laojun} -d ${DB_NAME:-laojun}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: laojun-redis
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-redis123}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 300
      --timeout 0
      --tcp-backlog 511
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - redis_logs:/var/log/redis
    networks:
      - laojun-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis123}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Nginx 反向代理
  nginx:
    image: nginx:stable-alpine
    container_name: laojun-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./test-nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - laojun-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  # 数据库管理工具 (开发环境)
  adminer:
    image: adminer:latest
    container_name: laojun-adminer
    ports:
      - "8090:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - laojun-network
    restart: unless-stopped
    profiles:
      - dev-tools

  # Redis 管理工具 (开发环境)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: laojun-redis-commander
    ports:
      - "8091:8081"
    environment:
      REDIS_HOSTS: "local:redis:6379:0:${REDIS_PASSWORD:-redis123}"
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    networks:
      - laojun-network
    restart: unless-stopped
    profiles:
      - dev-tools

# 网络配置
networks:
  laojun-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

# 数据卷
volumes:
  postgres_data:
    driver: local
  postgres_logs:
    driver: local
  redis_data:
    driver: local
  redis_logs:
    driver: local
  nginx_logs:
    driver: local