apiVersion: v2
name: taishanglaojun-monitoring
description: 太上老君微服务平台监控栈
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/codetaoist/laojun
sources:
- https://github.com/codetaoist/laojun
maintainers:
  - name: TaiShang LaoJun Team
    email: team@taishanglaojun.com
keywords:
  - monitoring
  - prometheus
  - grafana
  - jaeger
  - observability
annotations:
  category: Monitoring