# 太上老君监控系统配置文件
# Laojun Monitoring System Configuration

# 基础配置
environment: "development"
log_level: "info"
data_dir: "./data"

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  
  # TLS配置
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
  
  # 中间件配置
  middleware:
    # 日志中间件
    logging:
      enabled: true
      format: "json"
      include_request_body: false
      include_response_body: false
    
    # CORS中间件
    cors:
      enabled: true
      allowed_origins: ["*"]
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["*"]
      exposed_headers: []
      allow_credentials: false
      max_age: 86400
    
    # 认证中间件
    auth:
      enabled: false
      type: "jwt"
      secret: ""
      token_header: "Authorization"
      token_prefix: "Bearer "
    
    # 限流中间件
    rate_limit:
      enabled: false
      rate: 100
      burst: 200
      cleanup_interval: "1m"
    
    # 恢复中间件
    recovery:
      enabled: true
      stack_trace: true
    
    # 请求ID中间件
    request_id:
      enabled: true
      header: "X-Request-ID"

# 指标配置
metrics:
  enabled: true
  retention_period: "168h"  # 7天
  scrape_interval: "15s"
  max_samples: 1000000
  
  # 注册表配置
  registry:
    enabled: true
    namespace: "laojun"
    subsystem: "monitoring"

# 存储配置
storage:
  type: "memory"  # memory, file, database
  
  # 内存存储配置
  memory:
    max_size: "1GB"
    retention_period: "24h"
  
  # 文件存储配置
  file:
    directory: "./data/storage"
    max_file_size: "100MB"
    retention_period: "168h"  # 7天
    compression: true
  
  # 数据库存储配置
  database:
    type: "sqlite"  # sqlite, mysql, postgresql
    
    # SQLite配置
    sqlite:
      path: "./data/monitoring.db"
      pragma:
        journal_mode: "WAL"
        synchronous: "NORMAL"
        cache_size: 10000
    
    # MySQL配置
    mysql:
      host: "localhost"
      port: 3306
      username: "monitoring"
      password: ""
      database: "laojun_monitoring"
      charset: "utf8mb4"
      max_open_conns: 100
      max_idle_conns: 10
      conn_max_lifetime: "1h"
    
    # PostgreSQL配置
    postgresql:
      host: "localhost"
      port: 5432
      username: "monitoring"
      password: ""
      database: "laojun_monitoring"
      sslmode: "disable"
      max_open_conns: 100
      max_idle_conns: 10
      conn_max_lifetime: "1h"

# 告警配置
alerting:
  enabled: true
  evaluation_interval: "30s"
  
  # 告警规则
  rules: []
  
  # 接收器
  receivers: []
  
  # 路由
  routes: []

# 收集器配置
collectors:
  # 系统收集器
  system:
    enabled: true
    interval: "30s"
    cpu: true
    memory: true
    disk: true
    network: true
    load: true
    uptime: true
    processes: true
  
  # 应用收集器
  application:
    enabled: true
    interval: "15s"
    http: true
    runtime: true
    custom: true

# 日志配置
logging:
  # 日志管道
  pipelines: []

# 查询配置
query:
  enabled: true
  timeout: "30s"
  max_samples: 50000000
  
  # 查询引擎配置
  engine:
    timeout: "2m"
    max_samples: 50000000
    lookback_delta: "5m"

# 导出器配置
exporters:
  # Prometheus导出器
  prometheus:
    enabled: true
    path: "/metrics"
    
  # 文件导出器
  file:
    enabled: false
    path: "./data/exports"
    format: "json"
    interval: "1m"

# 追踪配置
tracing:
  enabled: false
  
  # Jaeger配置
  jaeger:
    endpoint: "http://localhost:14268/api/traces"
    service_name: "laojun-monitoring"
    
  # OTLP配置
  otlp:
    endpoint: "http://localhost:4317"
    service_name: "laojun-monitoring"

# 批处理器配置
batch_processor:
  enabled: true
  batch_size: 1000
  timeout: "1s"
  workers: 4