# Config Center Configuration - 本地开发环境
server:
  host: "0.0.0.0"
  port: 8087
  readTimeout: 30s
  writeTimeout: 30s

storage:
  type: file  # file, redis, database
  file:
    basePath: "./etc/laojun"
    watchDir: true
  redis:
    host: localhost
    port: 6379
    password: "redis123"
    db: 1
  database:
    host: localhost
    port: 5432
    user: laojun
    password: "laojun123"
    dbname: laojun_local
    sslmode: disable

security:
  apiKey: "local-dev-api-key"
  allowedIPs:
    - "127.0.0.1"
    - "::1"
    - "localhost"

logging:
  level: debug
  format: text
  output: both  # console, file, both
  file:
    path: "./logs/config-center.log"
    maxSize: 100MB
    maxBackups: 5
    maxAge: 30