# Database & cache configuration (example)
postgres:
  host: localhost
  port: 5432
  user: laojun
  password: "laojun123"
  dbname: laojun_dev
  sslmode: disable
redis:
  host: localhost
  port: 6379
  db: 0
  password: "redis123"
influxdb:
  url: "http://localhost:8086"
  token: ""
  org: "default"
  bucket: "metrics"
minio:
  endpoint: "http://localhost:9000"
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  bucket: "laojun"