# 太上老君微服务平台核心服务配置

# 命名空间配置
namespace:
  create: true
  name: "taishanglaojun"

# 全局配置
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# 镜像拉取密钥
imagePullSecrets: []

# 名称覆盖
nameOverride: ""
fullnameOverride: ""

# 服务发现组件配置
discovery:
  enabled: true
  replicaCount: 2
  
  image:
    repository: taishanglaojun/laojun-discovery
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8081
    metricsPort: 9090
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  # 自动扩缩容配置
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  
  # 日志级别
  logLevel: "info"
  
  # 健康检查配置
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# 监控组件配置
monitoring:
  enabled: true
  replicaCount: 2
  
  image:
    repository: taishanglaojun/laojun-monitoring
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8082
    metricsPort: 9091
  
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  # 自动扩缩容配置
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  
  # 日志级别
  logLevel: "info"
  
  # 健康检查配置
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Redis 配置
redis:
  enabled: true
  replicaCount: 1
  
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  
  auth:
    enabled: false
    password: ""
  
  service:
    type: ClusterIP
    port: 6379
  
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 8Gi
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Consul 配置
consul:
  enabled: true
  replicaCount: 3
  
  image:
    repository: consul
    tag: "1.17"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8500
    serflanPort: 8301
    serfwanPort: 8302
    serverPort: 8300
    dnsPort: 8600
  
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi
  
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# ServiceAccount 配置
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod 安全上下文
podSecurityContext:
  fsGroup: 2000

# 容器安全上下文
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# 节点选择器
nodeSelector: {}

# 容忍度
tolerations: []

# 亲和性
affinity: {}

# Pod 反亲和性
podAntiAffinity:
  enabled: false
  type: soft  # soft or hard

# 网络策略
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: taishanglaojun-monitoring
      ports:
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 9091

# 持久化存储
persistence:
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi