{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}-grafana
  namespace: {{ include "taishanglaojun-monitoring.namespace" . }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      {{- include "taishanglaojun-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "taishanglaojun-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "taishanglaojun-monitoring.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: grafana
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "taishanglaojun-monitoring.imageRepository" .Values.grafana.image }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ include "taishanglaojun-monitoring.imagePullPolicy" . }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.admin.username | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.admin.password | quote }}
            - name: GF_INSTALL_PLUGINS
              value: {{ join "," .Values.grafana.plugins | quote }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
            {{- if .Values.grafana.persistence.enabled }}
            - name: grafana-storage
              mountPath: /var/lib/grafana
            {{- end }}
      volumes:
        - name: grafana-config
          configMap:
            name: {{ include "taishanglaojun-monitoring.fullname" . }}-grafana-config
        - name: grafana-datasources
          configMap:
            name: {{ include "taishanglaojun-monitoring.fullname" . }}-grafana-datasources
        - name: grafana-dashboards-config
          configMap:
            name: {{ include "taishanglaojun-monitoring.fullname" . }}-grafana-dashboards-config
        - name: grafana-dashboards
          configMap:
            name: {{ include "taishanglaojun-monitoring.fullname" . }}-grafana-dashboards
        {{- if .Values.grafana.persistence.enabled }}
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ include "taishanglaojun-monitoring.fullname" . }}-grafana
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}