{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}-grafana
  namespace: {{ include "taishanglaojun-monitoring.namespace" . }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "taishanglaojun-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}