{{- if .Values.jaeger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}-jaeger
  namespace: {{ include "taishanglaojun-monitoring.namespace" . }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
spec:
  replicas: {{ .Values.jaeger.replicaCount }}
  selector:
    matchLabels:
      {{- include "taishanglaojun-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: jaeger
  template:
    metadata:
      labels:
        {{- include "taishanglaojun-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: jaeger
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "taishanglaojun-monitoring.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: jaeger
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "taishanglaojun-monitoring.imageRepository" .Values.jaeger.image }}:{{ .Values.jaeger.image.tag }}"
          imagePullPolicy: {{ include "taishanglaojun-monitoring.imagePullPolicy" . }}
          ports:
            - name: http
              containerPort: 16686
              protocol: TCP
            - name: grpc
              containerPort: 14250
              protocol: TCP
            - name: thrift-http
              containerPort: 14268
              protocol: TCP
            - name: thrift-compact
              containerPort: 6831
              protocol: UDP
            - name: thrift-binary
              containerPort: 6832
              protocol: UDP
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: SPAN_STORAGE_TYPE
              value: {{ .Values.jaeger.storage.type | quote }}
            {{- if eq .Values.jaeger.storage.type "elasticsearch" }}
            - name: ES_SERVER_URLS
              value: {{ .Values.jaeger.storage.elasticsearch.serverUrls | quote }}
            - name: ES_USERNAME
              value: {{ .Values.jaeger.storage.elasticsearch.username | quote }}
            - name: ES_PASSWORD
              value: {{ .Values.jaeger.storage.elasticsearch.password | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.jaeger.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}