{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "taishanglaojun-monitoring.namespace" . }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
    name: {{ include "taishanglaojun-monitoring.namespace" . }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}